title: UO Landscaper Mod
description: A mod for UO Landscaper that aims to provide clean, complete transition tables and random statics for modern Ultima Online maps.
theme: just-the-docs

url: https://norad32.github.io/uo-landscaper-mod

aux_links:
  UO Landscaper Mod on GitHub: https://norad32.github.io/uo-landscaper-mod/
