title: UO Landscaper Mod
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://norad32.github.io/uo-landscaper-mod

aux_links:
  Template Repository: https://norad32.github.io/uo-landscaper-mod/
